  - name: Install dnsmasq
    apt:
      name=dnsmasq
      state=present
    tags:
      - dns
      - dnsmasq

  - name: Configure dnsmasq
    template:
      src=dnsmasq.j2
      dest=/etc/dnsmasq.conf
    notify:
      - restart dnsmasq
    tags:
      - dns
      - dnsmasq
