  - name: Install firefox
    apt:
      name=firefox
      state=present
    tags:
      - gui
      - firefox

  - name: Find prefs.js
    shell: ls /home/vagrant/.mozilla/firefox/*.default/prefs.js
    register: firefox_prefs
    tags:
      - gui
      - firefox

  - name: Remove bad firefox preferences (about:config)
    lineinfile:
      dest={{firefox_prefs.stdout}}
      line="{{item}}"
      state=absent
    with_items:
      - user_pref(\"browser.pocket.enabled\", true);
      - user_pref(\"loop.enabled\", true);
      - user_pref(\"browser.cache.disk.enable\", true);
      - user_pref(\"browser.privatebrowsing.autostart\", false);
      - user_pref(\"browser.safebrowsing.enabled\", true);
      - user_pref(\"browser.safebrowsing.malware.enabled\", true);
      - user_pref(\"dom.storage.enabled\", true);
      - user_pref(\"media.peerconnection.enabled\", true);
      - user_pref(\"geo.enabled\", true);
      - user_pref(\"beacon.enabled\", true)
      - user_pref(\"browser.bookmarks.restore_default_bookmarks\", true);
      - user_pref(\"browser.search.suggest.enabled\", true);
      - user_pref(\"pref.privacy.disable_button.view_cookies\", true);
    tags:
      - gui
      - firefox

  - name: Add good firefox privacy preferences (about:config)
    lineinfile:
      dest={{firefox_prefs.stdout}}
      line="{{item}}"
      state=present
    with_items:
      - user_pref(\"beacon.enabled\", false);
      - user_pref(\"browser.cache.disk.enable\", false);
      - user_pref(\"browser.pocket.enabled\", false);
      - user_pref(\"browser.privatebrowsing.autostart\", true);
      - user_pref(\"browser.safebrowsing.enabled\", false);
      - user_pref(\"browser.safebrowsing.malware.enabled\", false);
      - user_pref(\"browser.search.defaultenginename\", \"DuckDuckGo\");
      - user_pref(\"browser.search.hiddenOneOffs\", \"Yahoo,Bing,Amazon.com,eBay,Twitter,Wikipedia (en)\");
      - user_pref(\"browser.search.suggest.enabled\", false);
      - user_pref(\"dom.storage.enabled\", false);
      - user_pref(\"geo.enabled\", false);
      - user_pref(\"geo.wifi.uri\", \"http://127.0.0.1\");
      - user_pref(\"loop.enabled\", false);
      - user_pref(\"media.peerconnection.enabled\", false);
      - user_pref(\"network.cookie.cookieBehavior\", 1);
      - user_pref(\"network.cookie.lifetimePolicy\", 2);
      - user_pref(\"pref.privacy.disable_button.view_cookies\", false);
    tags:
      - gui
      - firefox

  - name: Other good firefox preferences (about:config)
    lineinfile:
      dest={{firefox_prefs.stdout}}
      line="{{item}}"
      state=present
    with_items:
      - user_pref(\"browser.bookmarks.restore_default_bookmarks\", false);
      - user_pref(\"browser.fullscreen.animate\", false);
      - user_pref(\"browser.newtabpage.enabled\", false);
      - user_pref(\"browser.newtabpage.enhanced\", false);
      - user_pref(\"browser.panorama.animate_zoom\", false);
      - user_pref(\"browser.startup.homepage\", \"about:blank\");
      - user_pref(\"browser.tabs.animate\", false);
      - user_pref(\"distribution.canonical.bookmarksProcessed\", false);
      - user_pref(\"noscript.firstRunRedirection\", false);
    tags:
      - gui
      - firefox
